import type {SourceReviewData} from './sourceReview';
import type {Effort,ReferenceResult} from './options';
import type {RubricResult,ProcessingEffort,ReferenceCoverage,JuryTable,EffortReduction,JurySummary,CaseStudy} from './rubric';

export type InputMethod = 'file'|'text'|'url';
export type Role = 'source' | 'a' | 'b';
export type Side = 'a' | 'b';
export type Reference = {kind: 'example' | 'scope'; id: string};
export type Example = {id: string; title: string; description: string; has_report: boolean; has_source_review?:boolean};
export type Inputs = Record<Role, string> & {source_language: string; target_language: string};
export type Material = {text: string; sha256: string; filename: string; warnings: string[]};
export type Draft = {id: string; materials: Record<Role, Material>; source_language: string; target_language: string;pipeline_request_id?:string};
export type Scope = {id?: string; texts: Record<Role, string>; hashes: Record<Role, string>;
  ranges: Record<Role, {start: number; end: number; text_sha256: string}>;
  status: string; profile: string; source_language: string; target_language: string};
export type Finding = {id: string; side: Side; code: string; status: string;
  source_excerpt: string; current_text: string; should_be: string; why: string;
  why_ru: string | null; review_note_ru: string | null; repeated: boolean;
  anchors: Record<string, {status: string; ranges: {start: number; end: number}[]}>};
export type SideSummary = {candidates: number | null; text_candidates: number | null;
  apparatus_candidates: number | null; necessary_edits: number | null;
  by_code: Record<string, number> | null; disputed: number; unlocated: number;
  repeated: number; classification_conflicts: number};
export type GeneratedApparatusEvidence = {artifact_sha256:string;label_ru:string;scope_label_ru:string;
  quality_status:'not_adjudicated'; groups:{id:string;title_ru:string;purpose_ru:string;count:number;
    examples:{text:string;start:number;end:number;sha256:string}[]}[]};
export type ComparisonView = {id: string; title: string; description: string; scope: Scope;
  demonstration?:boolean;ratings:Ratings;decision_effort:DecisionEffort;
  rubric?:RubricResult|null;rubric_protocol?:boolean;reference_coverage?:ReferenceCoverage|null;processing_effort?:ProcessingEffort;
  jury?:JuryTable|null;effort_reduction?:EffortReduction|null;jury_summary?:JurySummary|null;case_study?:CaseStudy|null;
  effort:Effort;hadith:ReferenceResult|null;
  source_review: SourceReviewData | null;
  generated_apparatus: GeneratedApparatusEvidence | null;
  provenance: Record<string, string> | null;
  boundary_review: {note_ru: string; start_ru?: string; end_ru?: string;
    previous_review_id?: string; reviewer?: string} | null;
  apparatus: Record<Side, {number: number; text: string}[]> | null;
  references: {label: string; url: string}[] | null;
  summary: {source_chars: number; source_pages: number; negotiation_grade: boolean;
    measured: boolean; sides: Record<Side, SideSummary>; findings: Finding[]};
  run: {id: string; status: string; model: string; code_sha: string;
    protocol?:string;cost?:{reported_usd:string;unresolved_reserved_usd:string};
    calls: number; independence: Record<string, string>; report_sha256: string} | null;
  matched_example_id: string | null; live_enabled: false};

export type SideRating = {accuracy:number|null;terminology:number|null;readability:number|null;
  apparatus:number|null;total:number|null;apparatus_correctness:null;apparatus_basis:string;
  inventory:Record<string,number>;excluded:number;finding_ids:string[]};
export type Ratings = {version:string;kind:string;sides:Record<Side,SideRating>;
  winner:Side|'tie'|null;weights:{accuracy:number;apparatus:number}};

export type DecisionSide = {prior_decisions:number|null;accepted:number|null;rejected:number|null;
  prior_estimated_seconds:number|null;remaining_candidates:number|null;remaining_estimated_seconds:number|null;
  total_estimated_seconds:number|null;measured_seconds:number|null};
export type DecisionEffort = {version:string;seconds_per_decision:number;kind:'estimate';
  sides:Record<Side,DecisionSide>;remaining_reduction_percent:number|null};
