import type {SourceReviewData} from './sourceReview';

export type Role = 'source' | 'a' | 'b';
export type Side = 'a' | 'b';
export type Reference = {kind: 'example' | 'scope'; id: string};
export type Example = {id: string; title: string; description: string; has_report: boolean; has_source_review?:boolean};
export type Inputs = Record<Role, string> & {source_language: string; target_language: string};
export type Material = {text: string; sha256: string; filename: string; warnings: string[]};
export type Draft = {id: string; materials: Record<Role, Material>; source_language: string; target_language: string};
export type Scope = {id?: string; texts: Record<Role, string>; hashes: Record<Role, string>;
  ranges: Record<Role, {start: number; end: number; text_sha256: string}>;
  status: string; profile: string; source_language: string; target_language: string};
export type Finding = {id: string; side: Side; code: string; status: string;
  source_excerpt: string; current_text: string; should_be: string; why: string;
  why_ru: string | null; review_note_ru: string | null; repeated: boolean;
  anchors: Record<string, {status: string; ranges: {start: number; end: number}[]}>};
export type SideSummary = {candidates: number | null; text_candidates: number | null;
  apparatus_candidates: number | null; necessary_edits: number | null;
  by_code: Record<string, number> | null; disputed: number; unlocated: number;
  repeated: number; classification_conflicts: number};
export type GeneratedApparatusEvidence = {artifact_sha256:string;label_ru:string;scope_label_ru:string;
  quality_status:'not_adjudicated'; groups:{id:string;title_ru:string;purpose_ru:string;count:number;
    examples:{text:string;start:number;end:number;sha256:string}[]}[]};
export type ComparisonView = {id: string; title: string; description: string; scope: Scope;
  source_review: SourceReviewData | null;
  generated_apparatus: GeneratedApparatusEvidence | null;
  provenance: Record<string, string> | null;
  boundary_review: {note_ru: string; start_ru?: string; end_ru?: string;
    previous_review_id?: string; reviewer?: string} | null;
  apparatus: Record<Side, {number: number; text: string}[]> | null;
  references: {label: string; url: string}[] | null;
  summary: {source_chars: number; source_pages: number; negotiation_grade: boolean;
    measured: boolean; sides: Record<Side, SideSummary>; findings: Finding[]};
  run: {id: string; status: string; model: string; code_sha: string;
    calls: number; independence: Record<string, string>; report_sha256: string} | null;
  matched_example_id: string | null; live_enabled: false};
