export type Effort = {reduction_percent:number|null;edit_reduction_percent:number|null;
  sensitivity_percent:[number,number]|null;sides:Record<'a'|'b',{edits:number|null;units:number|null;excluded:number}>};
export type HadithCandidate = {id:string;collection:string;number:number|string;text:string;url:string;
  edition:string;retrieved_at:string;snapshot_sha256:string;english_text?:string;grade?:string};
export type HadithItem = {quote:string;status:string;candidate_count:number;candidates:HadithCandidate[]};
export type QuranItem = {quote:string;status:string;ayah?:string;surah_name?:string;label?:string|null;label_status?:string;verse_text?:string|null};
export type ReferenceResult = {status:string;detected_count?:number;limit_reached?:boolean;
  quran:{found:number;total:number;label_differs:number;items:QuranItem[]}|null;
  hadith:{found:number;total:number;by_collection:Record<string,number>;items:HadithItem[]}|null;
  official?:{source:string;status:string;limit_reached?:boolean;records:{quote:string;status:string;record:HadithCandidate|null}[]}};
export type RunState = {id:string|null;status:string;error:string|null};
