export type RubricEvidence={id:string;source_quote:string;translation_quote:string;kind:string;
  explanation_en:string;explanation_ru:string;verified:boolean};
export type RubricSide={score:number|null;status:string;explanation_en:string;explanation_ru:string;evidence:RubricEvidence[]};
export type RubricResult={version:string;winner:'a'|'b'|'tie'|null;totals:Record<'a'|'b',number|null>;
  criteria:{criterion:string;a:RubricSide;b:RubricSide}[];unique_defects:Record<'a'|'b',number>};
export type ProcessingSide={pipeline_seconds:number|null;audit_operations:number|null;editor_operations:number|null;
  simulated_seconds:number|null;total_seconds:number|null;reason?:string|null;job_id?:string|null;
  operations:{stage:string;chunk_id:string;edit_id:string;before:string;after:string}[]};
export type ProcessingEffort={sides:Record<'a'|'b',ProcessingSide>;version:string};
export type ReferenceCoverage=Record<'quran'|'hadith',{total:number;a:number;b:number}>;
export type JuryRow={key:string;kind:'criterion'|'coverage';a:number|null;b:number|null;
  level?:Record<'a'|'b',number|null>;found?:Record<'a'|'b',number>;total?:number};
export type JuryTable={version:string;rows:JuryRow[];totals:Record<'a'|'b',number|null>;winner:'a'|'b'|'tie'|null};
export type EffortSide={edits:number;defects:number;missing_quotations:number;review_minutes:number;minutes:number};
export type EffortReduction={version:string;minutes_per_edit:number;reduction_percent:number|null;a:EffortSide;b:EffortSide};
export type JurySummary={en:string[];ru:string[]};
export type CaughtDefect={id:string;criterion:string;source_quote:string;translation_quote:string;explanation_en:string;explanation_ru:string};
export type CaseStudy={a:CaughtDefect[];b:CaughtDefect[];kitabs_corrections:{stage:string;before:string;after:string}[]};
export type JudgeTotals={model:string;totals:Record<'a'|'b',number|null>;winner:'a'|'b'|'tie'|null;run_id?:string|null};
export type SecondOpinion={first:JudgeTotals;second:JudgeTotals;agree:boolean;
  rows:{key:string;first:Record<'a'|'b',number|null>;second:Record<'a'|'b',number|null>}[]};
