"""Persistence boundary for editorial versions, commands and timer ownership."""
from typing import Protocol


class EditorialRepository(Protocol):
    def create(self,state:dict,command:dict)->dict: ...
    def get(self,ident:str)->dict|None: ...
    def previous_command(self,ident:str,command:dict)->dict|None: ...
    def append(self,state:dict,expected_revision:int,command:dict)->dict: ...
    def events(self,ident:str)->list[dict]: ...
