"""Optional platform boundary. No platform database or SDK imports."""
from typing import Protocol


class PipelineResultReader(Protocol):
    def completed(self, job_id: str, source_sha256: str) -> dict: ...


class PipelinePort(PipelineResultReader, Protocol):
    def ready(self) -> bool: ...
    def upload(self, source: str, source_language: str, target_language: str) -> str: ...
    def create(self, document_id: str) -> str: ...
    def start(self, job_id: str) -> None: ...
    def status(self, job_id: str) -> dict: ...
